### ISSUE TITLE
Making "target" images

### ISSUE THREAD

**Issue by prp-e** [hiukim/mind-ar-js#177]
Greetings. 
I have a question, how target images are built? what do they have inside them which matters?
Thanks.

**Comment by shabarito** [comment]
Hello,
Have you checked this [link](https://blog.pictarize.com/how-to-choose-a-good-target-image-for-tracking-in-ar-part-1/)

**Comment by prp-e** [comment]
Hello. Yes, I did. But I still couldn't find out how to create target images on my own.

**Comment by prp-e** [comment]
I explored the codes of this repository and I found that the compiler uses OpenCV. If I know what functions are used, I may be able to make a target image compiler in python as well.

@hiukim

**Comment by hiukim** [comment]
If memory served me well, I think the compiler didn't rely on OpenCV. It requires webgl though. If you want to make one in python, you will need to rewrite the whole logic (which is currently a `gpu code`), so that is actually not straight forward. but feel free to go ahead.

I'm also closing this issue for now. Feel free to re-open if there is some new insight.
