### ISSUE TITLE
Pictarize issue

### ISSUE THREAD

**Issue by everythingability** [hiukim/mind-ar-js#186]
Hi,

I hope this is the right place. I have a pictarize bug 

https://gitter.im/web-augmented-reality/pictarize <- and this issues site doesn't seem to get a lot of traffic. 

If I should/could be better off using mind-ar-js do let me know... I love the ease of pictarize and plan to use it with students soon, but if it's ropey, I'll learn mind-ar 

Thanks 

Tom

**Comment by hiukim** [comment]
Hi Tom, the purpose of that gitter chatroom is more for community discussion. I'll personally try to look at this more often. Let me try to reply you over there.

Also, there is a support email in Pictarize `hello [at] pictarize.com`

I'm closing this issue here, coz the issues here are more towards mindar.
