### ISSUE TITLE
3D model rotation

### ISSUE THREAD

**Issue by mr339** [hiukim/mind-ar-js#194]
I have a question. Is there a way to rotate the models once they have appeared on the images? like gesture-detector and gesture-handler does in Ar.js or something equivalent to that?
https://github.com/fcor/arjs-gestures

**Comment by mr339** [comment]
> Since the clickable event is an a-frame builtin, I guess this extension can do something. [@wmurphyrd/aframe-super-hands-component](https://github.com/wmurphyrd/aframe-super-hands-component).

Thanks, i'll try it out

**Comment by mr339** [comment]
> Since the clickable event is an a-frame builtin, I guess this extension can do something. [@wmurphyrd/aframe-super-hands-component](https://github.com/wmurphyrd/aframe-super-hands-component).

sadly , it seems it doesn't work on models in AR

**Comment by hiukim** [comment]
A lot of these `gesture` libraries won't work. The reason is that they are trying to manipulate the pose of the camera (They change the rotation,position or the camera instead of the model to simulate the same effect of rotating the model) MindAR also require direct control over the pose of the camera, so there are conflicts.

If you want to rotate model, you have to actually rotate the model.

**Comment by demisquare** [comment]
[This](https://github.com/krsbx/mind-ar-ts/tree/main/src/gesture-action) porting of MindAR supports gesture actions from AR.js Gestures.

**Comment by karimnyumba** [comment]
Here is a sample on how to use gestures with MindAR @mr339 
https://github.com/karimnyumba/MindAR-Gestures
