### ISSUE TITLE
Data import error - RangeError: Extra bytes found at buffer

### ISSUE THREAD

**Issue by positlabs** [hiukim/mind-ar-js#257]
I have been getting this error intermittently while trying to load my image targets. 

`RangeError: Extra 5000 byte(s) found at buffer`

I took some random screenshots... terrible targets, but you can use these to reproduce the bug. 

<img width="569" alt="Screen Shot 2022-10-04 at 3 11 06 PM" src="https://user-images.githubusercontent.com/1918844/193907801-3fe80173-41b9-4473-a7a1-d00d688fab69.png">
<img width="499" alt="Screen Shot 2022-10-04 at 3 11 04 PM" src="https://user-images.githubusercontent.com/1918844/193907804-d15c0617-230f-434b-84f2-f42ffc584d7d.png">
<img width="454" alt="Screen Shot 2022-10-04 at 3 11 01 PM" src="https://user-images.githubusercontent.com/1918844/193907806-4838cde2-5b13-4c97-bdaf-f573841a7454.png">
<img width="533" alt="Screen Shot 2022-10-04 at 3 11 09 PM" src="https://user-images.githubusercontent.com/1918844/193907793-0624b23a-4c94-4e74-afd9-487fe55567a4.png">

Do the target images need to be a specific size? I tried 1024 square but it gave me the same error.

**Comment by divljikunic** [comment]
Can confirm this is happening. It seems to never appear when using certain markers, but always (or almost always) when using others. 
However when generating .mind again (using the same image that apparently works) also produces erroneous .mind. If the problem is even there, that is.

**Comment by divljikunic** [comment]
Upon further investigation this turned out to be a simple case of missing files, the path to the .mind 'imageTargetSrc' file was wrong.

Create-react-app (or webpack) can't know .mind files should be copied to a folder that will be served publicly, unless you specifically configure them to do so.

The error itself sounds strange and/or misleading but, in my case at least, was resolved. 

I suggest you copy your targets file (e.g. 'targets.mind') to your build folder (public, dist, or whatever the final destination of your app is called), then set:
```
<a-scene mindar-image="imageTargetSrc: ./targets.mind;" >
```

**Comment by positlabs** [comment]
I tested and confirmed this is the issue. Thanks for your insights @divljikunic!

@hiukim Do you think it would make sense to catch this error and emit something more descriptive?

**Comment by tranphuongthao2405** [comment]
I've encountered this in my project. I've moved my files to public folder and it works. Thanks.
