### ISSUE TITLE
Tutorial on how to make object stays visible even when the image target is lost

### ISSUE THREAD

**Issue by pedrorocha-net** [hiukim/mind-ar-js#38]
Considering that mind-ar has a huge potential and that use case is very usual, I'd like to help you create such tutorial/documentation page.

Do you already have in mind what changes are required to do so?

You mentioned that "If you want to do something like this, you can approach the problem by using the non-aframe library build, then include and modify the above aframe.js script", but it wasn't that clear to jump into the code and do it.

Any guidelines?

**Comment by hiukim** [comment]
@pedrorocha-net Sure, that would be nice! Appreciate the help.

Sorry, that part of documentation is kind of sketchy. I wasn't prepared to expose the `Controller` class in the first place. I try to elaborate a bit:

First of all, if you use the build without aframe, i.e. `https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@0.4.2/dist/mindar.prod-min.js`.  The only difference is that the `aframe` extension wasn't included. and the aframe extension is this file `https://github.com/hiukim/mind-ar-js/blob/master/src/aframe.js`. In the other words, you need to add a modified version of this file as part of your application code.

There are five imports at the top
```
const {Controller} = require('./controller');
const {UI} = require('./ui/ui.js');
require("aframe");
require("aframe-extras");
const Stats = require("stats-js");
```

You can include the official`aframe` and `aframe-extras` sources from cdn. `stats-js` is not really necessary, but you can still include the officlal one from cdn too. If you don't need the stats, just remove the relevant codes. replace `Controller` with `window.MINDAR.Controller`. In the other words,

You should copy that aframe.js file and change to something like this

```
const Controller = window.MINDAR.Controller;
// require("aframe");
// require("aframe-extras");
// const Stats = require("stats-js");
// const {UI} = require('./ui/ui.js');
....
```
Then in your html page, should be something like this
```
<head>
   <script src="https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@0.4.2/dist/mindar.prod-min.js
"></script>
    <script src="https://aframe.io/releases/1.2.0/aframe.min.js"></script>
   <script src={{AFRAME_EXTRA_LIKE_ABOVE}}</script>
   <script src={{STAT_JS_LIKE_ABOVE}}</script>
   <script src="./custom-aframe.js"></script>
  </head>
```

So that leaves `UI`, which turns out to be kind of complicated. They are the default UI, like scanning screen. If you don't need those, you can also remove it and create your custom UI, just comment out the relevant codes. If you want to keep it, then you need to port those in. They are not that complicated, but still take a little time I guess. The source is here `https://github.com/hiukim/mind-ar-js/blob/master/src/ui/ui.js`

If you managed to do those, then the app should be running like the original production build. Then you can start tweaking the aframe extension to suit specific needs.

Sorry, I know it's not straight forward. This is really not I originally expect people to do. but since people are asking how to achieve something the library wasn't supporting yet, I can only come up with this ugly solution for the moment.

**Comment by hiukim** [comment]
@pedrorocha-net 

Actually there is another easier way.  You can just clone the repo, and modify the `aframe.js` directly and make a custom build. But that means you are branching out from the master.

I guess depending on your intention. If you want to improve the library, and make the changes generic to common cases, then I can merge your update into master too.

**Comment by hbaugmentedreality** [comment]
Hi @pedrorocha-net @hiukim , it would be great if you can develop this option for everyone.   I mean, as an option in the library, so we all can use this option.  Thank you guys.

**Comment by pedrorocha-net** [comment]
Thanks for the guidelines @hiukim ! I'll work on top of your repo, for sure, so that anyone can benefit from that.
I'll update here when I have something.

**Comment by andreaslindahl** [comment]
@pedrorocha-net Did you manage to fix this functionality?

**Comment by nadakbar** [comment]
I would also like to know if this functionality is possible, so if the target is lost fof any reason then the model stays on screen and centers to the screen. Any quick fixes or hacks to get this to happen
